---
- name: Setup Docker and Deploy Web App
  hosts: webservers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3-pip
        - docker.io

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Copy app files
      copy:
        src: ./index.html
        dest: /tmp/index.html

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /tmp/Dockerfile

    - name: Build Docker image
      community.docker.docker_image:
        name: webapp:latest
        build:
          path: /tmp
        source: build

    - name: Run Docker container
      community.docker.docker_container:
        name: webapp
        image: webapp:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"
